// Docs: docs/architecture/mime-parser-implementation.md
//
// JTD (RFC 8927) → typed models, per language. The single source of truth is
// schema/models.jtd.json; this emits gen/ts/models.ts and gen/python/models.py. Run `npm run gen`;
// the SSOT drift test (test/ssot.test.ts) fails if the committed gen/ is stale. Covers the JTD forms
// this project uses: definitions, type, enum, elements, properties/optionalProperties, values, ref,
// nullable. (A full RFC 8927 codegen would also do discriminator/mapping — not needed here.)

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const TS_PRIM = { string: 'string', boolean: 'boolean', timestamp: 'string', float32: 'number', float64: 'number', int8: 'number', uint8: 'number', int16: 'number', uint16: 'number', int32: 'number', uint32: 'number' };
const PY_PRIM = { string: 'str', boolean: 'bool', timestamp: 'str', float32: 'float', float64: 'float', int8: 'int', uint8: 'int', int16: 'int', uint16: 'int', int32: 'int', uint32: 'int' };

function tsType(s) {
  let t;
  if (s.ref) t = s.ref;
  else if (s.enum) t = s.enum.map((v) => JSON.stringify(v)).join(' | ');
  else if (s.elements) t = `${tsType(s.elements)}[]`;
  else if (s.values !== undefined) t = `Record<string, ${Object.keys(s.values).length ? tsType(s.values) : 'unknown'}>`;
  else if (s.type) t = TS_PRIM[s.type] ?? 'unknown';
  else t = 'unknown';
  return s.nullable ? `${t} | null` : t;
}

function pyType(s) {
  let t;
  if (s.ref) t = s.ref;
  else if (s.enum) t = `Literal[${s.enum.map((v) => JSON.stringify(v)).join(', ')}]`;
  else if (s.elements) t = `List[${pyType(s.elements)}]`;
  else if (s.values !== undefined) t = `Dict[str, ${Object.keys(s.values).length ? pyType(s.values) : 'Any'}]`;
  else if (s.type) t = PY_PRIM[s.type] ?? 'Any';
  else t = 'Any';
  return s.nullable ? `Optional[${t}]` : t;
}

const PY_RESERVED = new Set(['from', 'class', 'def', 'import', 'return', 'global', 'lambda', 'pass', 'None', 'True', 'False', 'and', 'or', 'not', 'in', 'is', 'if', 'else', 'elif', 'while', 'for', 'try', 'except', 'finally', 'with', 'as', 'del', 'raise', 'yield', 'assert', 'async', 'await', 'nonlocal', 'break', 'continue']);
const pyKey = (k) => (PY_RESERVED.has(k) ? `${k}_` : k);

export function generate(jtd) {
  const defs = jtd.definitions ?? {};
  const tsBlocks = [];
  const pyBlocks = [];

  for (const [name, schema] of Object.entries(defs)) {
    if (schema.enum) {
      tsBlocks.push(`export type ${name} = ${schema.enum.map((v) => JSON.stringify(v)).join(' | ')};`);
      pyBlocks.push(`${name} = Literal[${schema.enum.map((v) => JSON.stringify(v)).join(', ')}]`);
      continue;
    }
    // object form (properties / optionalProperties)
    const req = Object.entries(schema.properties ?? {});
    const opt = Object.entries(schema.optionalProperties ?? {});

    const tsLines = [
      ...req.map(([k, v]) => `  ${k}: ${tsType(v)};`),
      ...opt.map(([k, v]) => `  ${k}?: ${tsType(v)};`),
    ];
    tsBlocks.push(`export interface ${name} {\n${tsLines.join('\n')}\n}`);

    const pyLines = [
      ...req.map(([k, v]) => `    ${pyKey(k)}: ${pyType(v)}`),
      ...opt.map(([k, v]) => `    ${pyKey(k)}: Optional[${pyType(v)}] = None`),
    ];
    pyBlocks.push(`@dataclass\nclass ${name}:\n${pyLines.length ? pyLines.join('\n') : '    pass'}`);
  }

  const banner = '// GENERATED by scripts/gen.mjs from schema/models.jtd.json — do not edit. Run `npm run gen`.';
  const ts = `${banner}\n// Docs: docs/architecture/mime-parser-implementation.md\n\n${tsBlocks.join('\n\n')}\n`;
  const py = `# GENERATED by scripts/gen.mjs from schema/models.jtd.json — do not edit. Run \`npm run gen\`.\n# Docs: docs/architecture/mime-parser-implementation.md\nfrom __future__ import annotations\nfrom dataclasses import dataclass\nfrom typing import Any, Dict, List, Literal, Optional\n\n${pyBlocks.join('\n\n')}\n`;
  return { ts, python: py };
}

// CLI: read the SSOT and write the generated files.
const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
if (process.argv[1] && process.argv[1].endsWith('gen.mjs')) {
  const jtd = JSON.parse(readFileSync(join(root, 'schema/models.jtd.json'), 'utf8'));
  const { ts, python } = generate(jtd);
  mkdirSync(join(root, 'gen/ts'), { recursive: true });
  mkdirSync(join(root, 'gen/python'), { recursive: true });
  writeFileSync(join(root, 'gen/ts/models.ts'), ts);
  writeFileSync(join(root, 'gen/python/models.py'), python);
  console.log('generated gen/ts/models.ts + gen/python/models.py');
}
